"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const _router_1 = __importDefault(require("./users/login/_router"));
const auth_1 = require("./../middleware/auth");
const _router_2 = __importDefault(require("./users/profile/_router"));
const _router_3 = __importDefault(require("./users/doctors/_router"));
const _router_4 = __importDefault(require("./users/hospitals/_router"));
const _router_5 = __importDefault(require("./users/appointment/_router"));
const _router_6 = __importDefault(require("./users/currentToken/_router"));
const _router_7 = __importDefault(require("./users/Folders/_router"));
const _router_8 = __importDefault(require("./users/schedule/_router"));
const _router_9 = __importDefault(require("./admin/login/_router"));
const _router_10 = __importDefault(require("./admin/hospital/_router"));
const _router_11 = __importDefault(require("./admin/profile/_router"));
const _router_12 = __importDefault(require("./doctor/login/_router"));
const _router_13 = __importDefault(require("./doctor/appointment/_router"));
const _router_14 = __importDefault(require("./doctor/profile/_router"));
const _router_15 = __importDefault(require("./doctor/hospital/_router"));
const _router_16 = __importDefault(require("./doctor/opdPatient/_router"));
const _router_17 = __importDefault(require("./doctor/ipdPatient/_router"));
const _router_18 = __importDefault(require("./doctor/bedType/_router"));
const _router_19 = __importDefault(require("./doctor/bed/_router"));
const _router_20 = __importDefault(require("./doctor/patient/_router"));
const _router_21 = __importDefault(require("./doctor/admission/_router"));
const _router_22 = __importDefault(require("./doctor/case/_router"));
const _router_23 = __importDefault(require("./doctor/doctor/_router"));
const _router_24 = __importDefault(require("./doctor/tokenNo/_router"));
const _router_25 = __importDefault(require("./doctor/specialization/_router"));
const _router_26 = __importDefault(require("./doctor/department/_router"));
const _router_27 = __importDefault(require("./doctor/qualification/_router"));
const _router_28 = __importDefault(require("./doctor/schedule/_router"));
const _router_29 = __importDefault(require("./doctor/holidays/_router"));
const _router_30 = __importDefault(require("./hospital/login/_router"));
const _router_31 = __importDefault(require("./hospital/profile/_router"));
const _router_32 = __importDefault(require("./hospital/appointment/_router"));
const _router_33 = __importDefault(require("./hospital/patient/_router"));
const _router_34 = __importDefault(require("./hospital/doctor/_router"));
const _router_35 = __importDefault(require("./hospital/admission/_router"));
const _router_36 = __importDefault(require("./hospital/patientCase/_router"));
const _router_37 = __importDefault(require("./hospital/bedType/_router"));
const _router_38 = __importDefault(require("./hospital/bed/_router"));
const _router_39 = __importDefault(require("./hospital/opdPatient/_router"));
const _router_40 = __importDefault(require("./hospital/ipdPatient/_router"));
const _router_41 = __importDefault(require("./hospital/caseHandler/_router"));
const _router_42 = __importDefault(require("./hospital/bedAssign/_router"));
const _router_43 = __importDefault(require("./hospital/specialization/_router"));
const _router_44 = __importDefault(require("./hospital/department/_router"));
const _router_45 = __importDefault(require("./hospital/qualification/_router"));
const _router_46 = __importDefault(require("./hospital/receptionist/_router"));
const _router_47 = __importDefault(require("./hospital/accounts/_router"));
const _router_48 = __importDefault(require("./hospital/appointmentTransaction/_router"));
const _router_49 = __importDefault(require("./hospital/bills/_router"));
const _router_50 = __importDefault(require("./hospital/payments/_router"));
const _router_51 = __importDefault(require("./hospital/advancePayment/_router"));
const _router_52 = __importDefault(require("./hospital/invoices/_router"));
const _router_53 = __importDefault(require("./hospital/prescriptions/_router"));
const _router_54 = __importDefault(require("./doctorWeb/appointment/_router"));
const _router_55 = __importDefault(require("./doctorWeb/doctor/_router"));
const _router_56 = __importDefault(require("./doctorWeb/patient/_router"));
const _router_57 = __importDefault(require("./doctorWeb/admission/_router"));
const _router_58 = __importDefault(require("./doctorWeb/opdPatient/_router"));
const _router_59 = __importDefault(require("./doctorWeb/ipdPatient/_router"));
const _router_60 = __importDefault(require("./doctorWeb/prescriptions/_router"));
const _router_61 = __importDefault(require("./receptionist/login/_router"));
const _router_62 = __importDefault(require("./receptionist/profile/_router"));
const app = (0, express_1.default)();
app.use("/doctor", _router_12.default);
app.use("/doctor/profile", auth_1.doctorAuth, _router_14.default);
app.use("/doctor/d", auth_1.doctorAuth, _router_23.default);
app.use("/doctor/hospital", auth_1.doctorAuth, _router_15.default);
app.use("/doctor/patient", auth_1.doctorAuth, _router_20.default);
app.use("/doctor/patient/admission", auth_1.doctorAuth, _router_21.default);
app.use("/doctor/appointment", auth_1.doctorAuth, _router_13.default);
app.use("/doctor/opd_patient", auth_1.doctorAuth, _router_16.default);
app.use("/doctor/ipd_patient", auth_1.doctorAuth, _router_17.default);
app.use("/doctor/bed_type", auth_1.doctorAuth, _router_18.default);
app.use("/doctor/bed", auth_1.doctorAuth, _router_19.default);
app.use("/doctor/patient/case", auth_1.doctorAuth, _router_22.default);
app.use("/doctor/token", auth_1.doctorAuth, _router_24.default);
app.use("/doctor/specialization", auth_1.doctorAuth, _router_25.default);
app.use("/doctor/department", auth_1.doctorAuth, _router_26.default);
app.use("/doctor/qualification", auth_1.doctorAuth, _router_27.default);
app.use("/doctor/schedule", auth_1.doctorAuth, _router_28.default);
app.use("/doctor/holidays", auth_1.doctorAuth, _router_29.default);
app.use("/patient", _router_1.default);
app.use("/patient/profile", auth_1.patientAuth, _router_2.default);
app.use("/patient/doctor", auth_1.patientAuth, _router_3.default);
app.use("/patient/hospital", auth_1.patientAuth, _router_4.default);
app.use("/patient/appointment", auth_1.patientAuth, _router_5.default);
app.use("/patient/current", auth_1.patientAuth, _router_6.default);
app.use("/patient/folder", auth_1.patientAuth, _router_7.default);
app.use("/patient/schedule", auth_1.patientAuth, _router_8.default);
app.use("/hospital", _router_30.default);
app.use("/hospital/doctor", auth_1.hospitalAuth, _router_34.default);
app.use("/hospital/patient", auth_1.hospitalAuth, _router_33.default);
app.use("/hospital/profile", auth_1.hospitalAuth, _router_31.default);
app.use("/hospital/appointment", auth_1.hospitalAuth, _router_32.default);
app.use("/hospital/admission", auth_1.hospitalAuth, _router_35.default);
app.use("/hospital/patient/case", auth_1.hospitalAuth, _router_36.default);
app.use("/hospital/patient/caseHandler", auth_1.hospitalAuth, _router_41.default);
app.use("/hospital/bed_type", auth_1.hospitalAuth, _router_37.default);
app.use("/hospital/bed", auth_1.hospitalAuth, _router_38.default);
app.use("/hospital/bed_assign", auth_1.hospitalAuth, _router_42.default);
app.use("/hospital/opd_patient", auth_1.hospitalAuth, _router_39.default);
app.use("/hospital/ipd_patient", auth_1.hospitalAuth, _router_40.default);
app.use("/hospital/specialization", auth_1.hospitalAuth, _router_43.default);
app.use("/hospital/department", auth_1.hospitalAuth, _router_44.default);
app.use("/hospital/qualification", auth_1.hospitalAuth, _router_45.default);
app.use("/hospital/receptionist", auth_1.hospitalAuth, _router_46.default);
app.use("/hospital/accounts", auth_1.hospitalAuth, _router_47.default);
app.use("/hospital/appointment-transaction", auth_1.hospitalAuth, _router_48.default);
app.use("/hospital/bills", auth_1.hospitalAuth, _router_49.default);
app.use("/hospital/payments", auth_1.hospitalAuth, _router_50.default);
app.use("/hospital/advance-payments", auth_1.hospitalAuth, _router_51.default);
app.use("/hospital/invoices", auth_1.hospitalAuth, _router_52.default);
app.use("/hospital/prescription", auth_1.hospitalAuth, _router_53.default);
app.use("/admin", _router_9.default);
app.use("/admin/hospital", auth_1.adminAuth, _router_10.default);
app.use("/admin/profile", auth_1.adminAuth, _router_11.default);
app.use("/users", _router_61.default);
app.use("/users/profile", auth_1.userAuth, _router_62.default);
// web
app.use("/web/appointment", auth_1.doctorAuth, _router_54.default);
app.use("/web/doctor", auth_1.doctorAuth, _router_55.default);
app.use("/web/patient", auth_1.doctorAuth, _router_56.default);
app.use("/web/patient/admission", auth_1.doctorAuth, _router_57.default);
app.use("/web/opd_patient", auth_1.doctorAuth, _router_58.default);
app.use("/web/ipd_patient", auth_1.doctorAuth, _router_59.default);
app.use("/web/prescription", auth_1.doctorAuth, _router_60.default);
exports.default = app;
