import { model } from "mongoose";
import { patientSchema } from "../models/patient";
import { hospitalSchema } from "../models/hospital";
import { doctorSchema } from "../models/doctor";
import { appointmentSchema } from "../models/appointment";
import { adminSchema } from "../models/admin";
import { admissionSchema } from "../models/admission";
import { patientCaseSchema } from "../models/patientCase";
import { caseHandlerSchema } from "../models/caseHandler";
import { bedTypeSchema } from "../models/bedType";
import { bedAssignSchema } from "../models/bedAssign";
import { bedSchema } from "../models/bed";
import { opdPatientSchema } from "../models/opdPatient";
import { ipdPatientSchema } from "../models/ipdPatient";
import { tokenNoSchema } from "../models/tokenNo";
import { folderSchema } from "../models/folderOfPatient";
import { specializationSchema } from "../models/specialization";
import { departmentSchema } from "../models/department";
import { qualificationSchema } from "../models/qualification";
import { scheduleSchema } from "../models/schedule";
import { holidaySchema } from "../models/doctorHolidays";
import { usersSchema } from "../models/users";
import { accountsSchema } from "../models/accounts";
import { appointmentTransactionsSchema } from "../models/appointmentTransaction";
import { billsSchema } from "../models/bills";
import { billItemsSchema } from "../models/billItems";
import { billTransactionSchema } from "../models/billTransaction";
import { paymentSchema } from "../models/payment";
import { advancePaymentSchema } from "../models/advancePayment";
import { invoiceSchema } from "../models/invoices";
import { invoiceItemSchema } from "../models/invoiceItems";
import { prescriptionsMedicinesSchema } from "../models/prescriptionsMedicines";

export default () => {
  model("Patients", patientSchema);
  model("Hospitals", hospitalSchema);
  model("Doctors", doctorSchema);
  model("Appointment", appointmentSchema);
  model("Admin", adminSchema);
  model("Admission", admissionSchema);
  model("PatientCase", patientCaseSchema);
  model("CaseHandler", caseHandlerSchema);
  model("BedType", bedTypeSchema);
  model("Bed", bedSchema);
  model("BedAssign", bedAssignSchema);
  model("OpdPatient", opdPatientSchema);
  model("IpdPatient", ipdPatientSchema);
  model("TokenNo", tokenNoSchema);
  model("Folders", folderSchema);
  model("Specialization", specializationSchema);
  model("Department", departmentSchema);
  model("Qualification", qualificationSchema);
  model("Schedule", scheduleSchema);
  model("Holidays", holidaySchema);
  model("Users", usersSchema);
  model("Accounts", accountsSchema);
  model("AppointmentTransaction", appointmentTransactionsSchema);
  model("Bills", billsSchema);
  model("BillItems", billItemsSchema);
  model("BillTransaction", billTransactionSchema);
  model("Payments", paymentSchema);
  model("AdvancePayment", advancePaymentSchema);
  model("Invoices", invoiceSchema);
  model("InvoiceItems", invoiceItemSchema);
  model("PrescriptionsMedicines", prescriptionsMedicinesSchema);
};
